name: Output information
on: issues

jobs:
  info:
    runs-on: windows-latest
    steps:
      - name: Output GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$env:GITHUB_CONTEXT"
