name: Output imformation
on: workflow_dispatch

jobs:
  info:
    runs-on: windows-latest
    steps:
      - name: Output GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$env:GITHUB_CONTEXT"
